Fix Typescript errors
 src/index.ts(604,164): error TS2638: Type '{}' may represent a primitive value, which is not permitted as the right operand of the 'in' operator.
src/index.ts(608,26): error TS2339: Property 'value' does not exist on type 'PromiseSettledResult<unknown>'.
  Property 'value' does not exist on type 'PromiseRejectedResult'.
src/index.ts(613,36): error TS2339: Property 'value' does not exist on type 'PromiseSettledResult<unknown>'.
  Property 'value' does not exist on type 'PromiseRejectedResult'.
src/index.ts(618,42): error TS2339: Property 'value' does not exist on type 'PromiseSettledResult<unknown>'.
  Property 'value' does not exist on type 'PromiseRejectedResult'.
src/index.ts(855,26): error TS2454: Variable 'nwsAlertData' is used before being assigned.
src/index.ts(856,23): error TS18048: 'nwsAlertData' is possibly 'undefined'.
src/index.ts(939,61): error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.